### ISSUE TITLE
Compatible version of j4ts with JSweet 1.2.0 release

### ISSUE THREAD

**Issue by sadevelopment** [j4ts/j4ts#10]
Could we get a release that is compatible with the recent 1.2.0 release of JSweet?

**Comment by renaudpawlak** [comment]
Unless I am mistaking, I think that org.jsweet.candies:j4ts-0.3.0-SNAPSHOT is compatible. Do you want me to release 0.3.0?

**Comment by sadevelopment** [comment]
So what we are trying to achieve is having a version of j4ts that has been built using your latest prod jsweet-transpiler release. It looks like 0.3.0-SNAPSHOT is using 1.1.1 of the transpiler.

**Comment by renaudpawlak** [comment]
Right. Version 1.2 is an intermediate release before version 2. Version 2 will be more open than version 1.x, which will allow everybody to modify candies and contribute easily. The core reason behind it is that we want to give more freedom to the users since maintaining all the candies ourselves it too much of a work. 

So, since 1.2 is fully compatible with 1.1.1 candies, I have decided not to release any candies for that version. You should still use 1.1.1 candies, even if you get warnings. All this will be fixed soon with version 2. Of course, if you find an issue with the candy, please tell me and we will fix it.

**Comment by renaudpawlak** [comment]
Please note the 0.5.0-SNAPSHOT, (develop/v0.5.0 branch) which is now compatible with JSweet v2.
