### ISSUE TITLE
HashSet.remove not working correctly for non-present values

### ISSUE THREAD

**Issue by nidefawl** [j4ts/j4ts#22]
The transpiler outputs following code for the HashSet.remove function:
` /* remove */ (function (a) { return a.splice(a.indexOf(sy), 1); })(canditates);`
When trying to remove a non-present value it will result in the array being spliced at index -1.
The resulting operation will remove the last entry from the array.

In java the HashSet stays unmodified when trying to remove non-present values.

A simple workaround on the java side is of course checking for existence of values before attempted removal.

**Comment by renaudpawlak** [comment]
That's a bad one. But actually it's not a J4TS issue. If you were using J4TS, you would have the ``HashSet`` class at runtime and the generated code would be ``candidates.remove(sy)``. Here since JSweet substitutes the ``remove`` invocation with pure JavaScript code, it means that you don't have the J4TS runtime in your classpath (you should check this because if you have it, then it is another type of issue that we also want to fix).

So, I am moving this issue to JSweet: https://github.com/cincheo/jsweet/issues/373. Thanks.

**Comment by nidefawl** [comment]
You are right, I don't have J4TS in my classpath.
